### ISSUE TITLE
TestClass gibt auf Linux nur letzte 3 Ziffern aus

### ISSUE THREAD

**Issue by microGen** [microGen/BMT3-SEP-Pr4#11]
Auf Windows scheint TestClass alle 4 Ziffern auszugeben

**Comment by Code-Dog** [comment]
In der Dropbox liegt eine modifizierte und kürzere Testclass. Bitte einmal im Unit-Test einbauen und unter Linux testen.
Die Verwendete Funktion liefert einen unsigned long int Wert zurück. Es ist die einzige Funktion die ich gefunden habe für string to unsigned.

**Comment by microGen** [comment]
Jo, läuft!
Habe deinen Kommentar nicht gesehen und selber ein wenig rumgeschaut: die if-Bedingung hier:
`if (zeile[j] == ' ') {`
`                    j++;`
`                    continue;`
`                }`
schien problematisch zu sein...nachdem ich sie wegkommentiert und j auf die erste Ziffer gesetzt habe, lief es auch. Aber deine neue Lösung ist besser.

**Comment by jocogergely** [comment]
Mit dem neue Version sollte es funktionieren

**Comment by microGen** [comment]
Siehe Branch `NewTestClass`

**Comment by microGen** [comment]
**DONE**
