### ISSUE TITLE
Mittelwertbildung im HeightSensor resultiert in SegFault

### ISSUE THREAD

**Issue by microGen** [microGen/BMT3-SEP-Pr4#12]
`this->sensors = sensors;`
 `int median = 0;`

`       for (int i = 0; i < 10; i++) {`
`           sample = sensors->getHight();`
`           median = (median + sample) / i;     // gemittelte Distanz zum Band`
`       }`

**Comment by microGen** [comment]
in for-Schleife wird durch 0 geteilt :sweat_smile:

**Comment by microGen** [comment]
Der Fehler liegt in `getHight()`.

Ich habe das Problem mit einem extra Unit-Test simuliert. Das Programm liegt auf der Dropbox unter "Mittelwert-Verifizierung".
Statt TestClass habe ich eine mini-Klasse namens "Unittest" gebaut, die das Problem testet.

**Comment by jocogergely** [comment]
wenn das am getHigt liegen sollte, dann musste es mit dem neue Version von TestClass funktionieren!

**Comment by microGen** [comment]
D'accord, ausprobiert und funktioniert mit TestClass der Branch "NewTestClass"
