### ISSUE TITLE
Höhenzuweisung gibt konstant Fehlerzustand aus

### ISSUE THREAD

**Issue by microGen** [microGen/BMT3-SEP-Pr4#13]
Nach erstem Messwert bleibt Höhenzuweisung konstant im Fehlerzustand.
`if (sample > dist_grund && prev_value != 1){`
`        MusterMeasure.push_back(1);`
`} [...] else {`
        `cout << "Ihr n00bs habt Mist gebaut!\n";`
`}`

geht immer in Fehlerzustand über, wenn ein gleicher Messwert vorher schon existierte.
Ergo: Fehlerzustand muss intelligenter implementiert oder weggelassen werden.

**Fix:** `else if(sample out of bounds){[...]}`
_will implement this later_

**Comment by jocogergely** [comment]
Also im TestClass daten einlesen funktioniert? Baucht ihr das nicht mehr?

**Comment by Code-Dog** [comment]
Funktioniert und ist im Unit-Test integriert. Siehe Dropbox. 
Ich denke die 3 Zeichen bei Linux liegen an der Signed Integer zu Unsigned Short Konvertierung.
Probier mal (unsigned short) atoi(...) oder eine andere Typconversion. Es gibt keine Alternative zu atoi. Stoi läuft, es sei den jemand will sich mit Boost Integration beschäftigen.

**Comment by microGen** [comment]
Gut, werde es ausprobieren. Thx

**Comment by microGen** [comment]
**DONE**
