### ISSUE TITLE
Dokumentation Template

### ISSUE THREAD

**Issue by KnabeBen** [microGen/BMT3-SEP-Pr4#17]
FINISH AS SOON AS POSSIBLE!!!!!!!!!!!!

Bitte selbstständig Aufgaben übernehmen und als einzelnen Ordner/Datei in die Dropbox stellen. Ben stellt alles zusammen

**MITTWOCH FERTIG!!!!!!!!!**

**Comment by KnabeBen** [comment]
- [ ] Klassendiagramm

- [ ] Schwierigkeiten während des Projektes

- [ ] Integrationstest 

- [ ] Design

**Comment by microGen** [comment]
Klassendiagramm ist ja schon vorhanden, muss modifiziert werden.
Was meinst du mit Design? SW-Design?

Wer macht was?
Soll ich was zu den Schwierigkeiten schreiben?

**Comment by microGen** [comment]
Eventuell noch Code ein wenig kommentieren?
Dann muss man eventuell nicht so lang und breit Fließtext schreiben

**Comment by microGen** [comment]
Kann jeder noch mal schreiben, für welchen Code-Teil er (Haupt)verantwortlicher war? In meiner Erinnerung:
**BK:** 
**CF:** TestClass
**JG:** FSM
**NW:** HeightSensor

**Comment by microGen** [comment]
Fazit **NW** done

**Comment by microGen** [comment]
Überarbeitung Testcase Unit Test **done**
**Achtung:** Habe Glossar auch überarbeitet.
Datei liegt mit im Dokumentationsordner

**Comment by microGen** [comment]
Habe den **Milestone Abgabe** an dieses Issue rangehängt. Nette Deadline-Funktion :+1:

**Comment by jocogergely** [comment]
Überarbeitung von FSM **done**

**Comment by microGen** [comment]
Ok, mit der Abgabe würde ich das hier als **DONE** bezeichnen. **ENDE**
