### ISSUE TITLE
Code-Schwund: in FSM fehlt Aufruf von result()

### ISSUE THREAD

**Issue by microGen** [microGen/BMT3-SEP-Pr4#18]
Im State "wait" fehlt der Aufruf von `HeightSensor->result` zum Löschen des Messmusters.
**Bitte einpflegen**

**Comment by microGen** [comment]
Oder mir schreiben, wo / wie diese Methode implementiert war. Habe keinen Überblick auf Implementation gehabt.

**Comment by KnabeBen** [comment]
HeightSensor->result   muss im State "Transport" aufgerufen werden.

**Comment by Code-Dog** [comment]
Ist immernoch vorhanden in der Zip-Datei unter Abgabe. Der Aufruf findet im Ready statt auf dem Weg zum Transport. Es ist auch im GitHub Abgabe vorhanden.

**Comment by microGen** [comment]
Oh derpedidoo! Sorry guys, komplett übersehen!
Da hat auch mal die Ausgabe des Bauteilszustandes bei unidentifizierten Muster gefehlt. Hab's aber schon selber wieder hinzugefügt.
Allright, **closed**
